name: GCP Deploy Check

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure Docker for Artifact Registry'
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: 'Build Docker image'
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/go-cloudrun-example:${{ github.sha }} .