version: '3.8'

services:
  firestore-emulator:
    build:
      context: .
      dockerfile: firestore.Dockerfile
    command: ["gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Map container port 8080 to host port 8081
    environment:
      PROJECT_ID: local-test # Using a dummy ID for local testing
      FIRESTORE_EMULATOR_HOST: firestore-emulator:8080
      PORT: 8080
    depends_on:
      firestore-emulator:
        condition: service_healthy
